
        


name: Export my notion workspace

on:

workflow_dispatch: {}

jobs:
export:
runs-on: ubuntu-latest
steps:
- uses: igor-kupczynski/notion-exporter@v1.0.2
with:
pages: "256a6545727e44e6bc60566b5d636443"  # Pages IDs identified in (step 2)
output-dir: Carl-Camp
notion-token: ${{ secrets.NOTION_TOKEN }}
github-token: ${{ secrets.GITHUB_TOKEN }}
