name: Export my notion workspace

on:
  schedule:
    - cron: "0 */1 * * *"  # Call the export every 6 hours
  workflow_dispatch: {}

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: igor-kupczynski/notion-exporter@v1.0.2
        with:
          pages: "33becf164357401cae56646404667ff6"  # Pages IDs identified in (step 2)  
          output-dir: Carl-Camp
          notion-token: ${{ secrets.NOTION_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
